version: 2
jobs:
  build:
    docker:
      - image: cryptogoth/node-circle-test:663bbd5
    steps:
      - checkout
      - run: . ~/.profile; lerna bootstrap
      - run:
          command: . ~/.profile; ganache-cli -p 8545
          background: true
      - run:
          shell: /bin/sh
          command: |
            sleep 7 && wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=15 -t 10 http://localhost:8545
            :
      - run: . ~/.profile; cd packages/rest; yarn start
      - run: . ~/.profile; lerna run test
